### ISSUE TITLE
Purpose of Event Completed tag?

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/events#1]
I see some completed events have `event completed` tag and some do not. Does the tag still serve a purpose? Can we avoid a step by omitting it, or should I add it to past events?

**Comment by jules32** [comment]
Hi! Yes I was starting the process of omitting the `event completed` tag and thought that is something we can do as we migrate to quarto since we'll need to review each post!

**Comment by stefaniebutland** [comment]
closing issue since we're removing tag in quarto version
