### ISSUE TITLE
commit result not showing in live page

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/events#16]
@jules32 I just noticed this; do you know how to resolve?

[Live page](https://openscapes.github.io/events/posts/2022-06-09-hello-quarto/) of Hello Quarto not up to date with [commit that added link to blog post](https://github.com/Openscapes/events/pull/15/commits/3a1637870e13fa75b8342fe3d0d5d849f6550a73) in this [pull request](https://github.com/Openscapes/events/pull/15)

![Screen Shot 2022-11-15 at 8 52 06 AM](https://user-images.githubusercontent.com/11927811/201979000-65378574-d1bb-4aef-9dda-ec453b8e398c.png)

![Screen Shot 2022-11-15 at 8 52 56 AM](https://user-images.githubusercontent.com/11927811/201979100-647732be-3dd7-468b-a5bf-7e536cb16b5c.png)

**Comment by jules32** [comment]
Hi @stefaniebutland , did you make this edit from the browser?

I pulled locally and when I did "preview website" in RStudio I saw the same behavior you saw. But when I rendered the specific qmd file (hello-quarto/index.qmd), your edits were incorporated (and are now live). 

If you had made your edits from the browser, this would be consistent with Quarto's default blog behavior where it doesn't re-build all posts when you render/preview the website as a whole - you have to specifically tell it to rebuild certain pages

**Comment by stefaniebutland** [comment]
ah yes, did from browser. Wasn't aware of this behavior. Thanks!
