### ISSUE TITLE
Add June 9 Hello Quarto community call 

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/events#2]
https://github.com/Openscapes/how_we_work/issues/145

**Comment by jules32** [comment]
Awesome, excited to talk through this together tomorrow!

**Comment by stefaniebutland** [comment]
May 5th Julie & Stef created a place-holder for this (https://github.com/Openscapes/events/tree/helloquarto), and Julie has updated the text in our comm call google doc. Stef will update. Would be nice to have Hello Quarto announced on a Quarto Event page, eh?

**Comment by stefaniebutland** [comment]
Page is live! https://openscapes.github.io/events/posts/2022-06-09-hello-quarto/
