### ISSUE TITLE
Banner saying "this site is deprecated" not publishing

### ISSUE THREAD

**Issue by jules32** [Openscapes/events#26]
Not sure why this has not rebuilt: https://github.com/Openscapes/events/blob/main/_quarto.yml#L5

**Comment by stefaniebutland** [comment]
@jules32 can we / I archive this repo? We did that with rOpenSci stuff. Gets a clear banner 
![Screenshot 2023-09-21 at 12 47 47 PM](https://github.com/Openscapes/events/assets/11927811/2f9ea1d7-06b1-4f96-8570-9a6c03b860ad)

## Settings:
![Screenshot 2023-09-21 at 12 44 53 PM](https://github.com/Openscapes/events/assets/11927811/c8f06eb5-be7a-486e-91b1-af3994ccda47)

**Comment by jules32** [comment]
Yes please! thanks @stefaniebutland

**Comment by stefaniebutland** [comment]
closing issue and archiving!
